apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: diabetes-predictor
  namespace: diabetes-model
spec:
  predictor:
    serviceAccountName: sa-s3-access
    sklearn:
      storageUri: s3://diabetes-model-bucket/models/
