apiVersion: v1
kind: Namespace
metadata:
  name: diabetes-model
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: diabetes-model
  annotations:
    serving.kserve.io/s3-endpoint: s3.amazonaws.com
    serving.kserve.io/s3-usehttps: "1"
    serving.kserve.io/s3-region: us-east-1
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "mock_key_id"
  AWS_SECRET_ACCESS_KEY: "mock_secret_key"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-s3-access
  namespace: diabetes-model
secrets:
  - name: s3-secret
