apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-sa
  namespace: diabetes-mlops
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: diabetes-mlops
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "mock_key_id"
  AWS_SECRET_ACCESS_KEY: "mock_secret_key"
